spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb:8080/h2
    username: sa
    password: 1234
    platform: h2
  jpa:
    hibernate:
      ddl-auto: update
  database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  port: 8088
